Increment 3
AllStars123/urlshortner pull request #2
Opened 2022-09-05 21:51 UTC by AllStars123

2022-09-12 08:39 UTC, lostsequence requested changes

2022-09-12 08:39 UTC, lostsequence commented on internal/shortner/shortner.go
> +func Shortner(longUrl string) string {
Думаю лучше Shorten назвать, чтобы имя отражало действие

2022-09-12 08:39 UTC, lostsequence commented on internal/shortner/shortner.go
> +	fmt.Println(split)
fmt.Println наверное остался от дебага ?

2022-09-12 08:39 UTC, lostsequence commented on internal/handlers/handlers.go
> +		}
Лучше добавить валидацию URL, чтобы редирект нормально сработал.
Можно использовать url.Parse или ParseRequestURI
И добавить кейс в тесты

2022-09-12 08:39 UTC, lostsequence commented on internal/handlers/handlers.go
> +			result["detail"] = err.Error()
Может лучше result["error"]/result["errorMessage"]/result["errorDetails"] ?

2022-09-12 08:39 UTC, lostsequence commented on internal/handlers/handlers.go
> +func CreateShortURL(data url.Values) func(c *gin.Context) {
urv.Values имеет тип map[string]string[] , нам слайс в принципе не нужен и лучше свой стор использовать типа map[string]string, абстрагироваться и не привязываться к url.

2022-09-12 08:39 UTC, lostsequence commented on internal/handlers/handlers.go
> +			result["detail"] = "Bad request"
Думаю тут можно не дублировать Bad Request, в принципе из статуса будет понятно.

2022-09-12 08:39 UTC, lostsequence commented on internal/shortner/shortner.go
> +	urlHash := base64.URLEncoding.EncodeToString(hasher.Sum(nil))
Можно немного сократить короткую ссылку :) взять срез меньшей длины

2022-09-12 08:39 UTC, lostsequence commented on internal/shortner/shortner.go
> +	if len(split) < 2 {
Почему здесь такой хитрый сплит ? Может сразу вместе с http encode сделать ?

2022-09-12 08:39 UTC, lostsequence commented on internal/handlers/handlers_test.go
> +				statusCode:  404,
Лучше хардкод статус кодов константами из http заменить

2022-09-13 21:58 UTC, AllStars123 commented on internal/shortner/shortner.go
> +	if len(split) < 2 {
Добрый вечер! Сплит вроде не хитрый, небольшая валидация идёт, что если приходит ссылка без `https://` , то мы сразу хешируем полученную ссылку.

2022-09-13 22:00 UTC, AllStars123 commented on internal/handlers/handlers.go
> +func CreateShortURL(data url.Values) func(c *gin.Context) {
Добрый вечер! Не особо понял. Я попробовал создать свой тип `type store map[string]string`, но тогда у меня не будет возможности использовать `Set()`

2022-09-17 18:25 UTC, lostsequence requested changes

2022-09-17 18:25 UTC, lostsequence commented on internal/handlers/handlers.go
> +func CreateShortURL(data url.Values) func(c *gin.Context) {
Да, всё верно. В мапу можно посетить просто по ключу:
```
var urlStore = make(map[string]string)
urlStore[key] = value
```

Либо создать структуру/интерфейс и реализовать метод Set. Например:
```
type URLStorage struct {
	urlStore map[string]string
}

func (us URLStorage) SetURL(shortURL string, originalURL string) {
	us.urlStore[shortURL] = originalURL
}

func (us URLStorage) GetURL(shortURL string) (string, bool) {
	originalURL, ok := us.urlStore[shortURL]
	if !ok {
		return "", false
	}

	return originalURL, true
}
```
Можно просто создать кастомный тип с методами:
```
type URLStorage map[string]string

func (us URLStorage) SetURL(shortURL string, originalURL string) {
	us[shortURL] = originalURL
}

func (us URLStorage) GetURL(shortURL string) (string, bool) {
	originalURL, ok := us[shortURL]
	if !ok {
		return "", false
	}

	return originalURL, true
}
```

2022-09-17 18:25 UTC, lostsequence commented on internal/shortner/shortner.go
> +	if len(split) < 2 {
Добрый :)
С учетом валидации, без протокола не пройдет
Если без валидации, не очень понятна суть сплита.
В чем принципиальная разница хеша "http://google.com" или "google.com" ?

И сейчас есть ошибка данного алгоритма.
В случае, когда пользователь захочет добавить два одинаковых урла но с разными протоколами, например:
"https://mysite.com" и "http://mysite.com", если обрезать "http" и "https", то у них будет одинаковый хеш и значение перезапишется, но ссылки то по сути свой разные.

2022-09-19 09:00 UTC, lostsequence approved these changes
Оставил немного комментариев по оформлению.

2022-09-19 09:00 UTC, lostsequence commented on internal/shortner/shortner.go
> +func Shorten(longURL string) string {
Я так понял, что Shorten только внутри пакета используется. Можно сделать приватным.

2022-09-19 09:00 UTC, lostsequence commented on internal/handlers/handlers_test.go
> +func setupRuter(data storages.URLStorage) *gin.Engine {
Опечатка: "router"

2022-09-19 09:00 UTC, lostsequence commented on internal/shortner/shortner.go
> +	if result == "" {
Думаю лучше в if на ok ориентироваться.

2022-10-03 21:51 UTC, merged